### ISSUE TITLE
Error when installing Splam via pip and conda

### ISSUE THREAD

**Issue by ArnavBharti** [Kuanhao-Chao/splam#4]
### Environment:
```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
bzip2                     1.0.8                hd590300_5    conda-forge
ca-certificates           2023.11.17           hbcca054_0    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
libexpat                  2.5.0                hcb278e6_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 13.2.0               h807b86a_3    conda-forge
libgomp                   13.2.0               h807b86a_3    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libsqlite                 3.44.2               h2797004_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
ncurses                   6.4                  h59595ed_2    conda-forge
openssl                   3.2.0                hd590300_1    conda-forge
pip                       23.3.2             pyhd8ed1ab_0    conda-forge
python                    3.12.1          hab00c5b_1_cpython    conda-forge
readline                  8.2                  h8228510_1    conda-forge
setuptools                69.0.3             pyhd8ed1ab_0    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
tzdata                    2023d                h0c530f3_0    conda-forge
wheel                     0.42.0             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge

Running Linux Mint Victoria 21.3 and Conda 23.3.1 (Accessed using Mamba)
```

### Through Bioconda
```
$ mamba install -c bioconda splam
```
#### Error: 
```
does not exist (perhaps a typo or a missing channel).
```
####  Detailed Log: 
```
Pinned packages:
  - python 3.12.*


Could not solve for environment specs
The following package could not be installed
└─ splam   does not exist (perhaps a typo or a missing channel).
```

### Through pip
```
$ pip install splam
```
#### Error:
```
error: metadata-generation-failed
```
#### Detailed Log:
```
Collecting splam
  Using cached splam-1.0.10.tar.gz (41.4 MB)
  Preparing metadata (setup.py) ... done
INFO: pip is looking at multiple versions of splam to determine which version is compatible with other requirements. This could take a while.
  Using cached splam-1.0.9.tar.gz (40.9 MB)
  Preparing metadata (setup.py) ... done
  Using cached splam-1.0.8.tar.gz (41.0 MB)
  Preparing metadata (setup.py) ... done
  Using cached splam-1.0.7.tar.gz (40.9 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-2qrm2225/splam_5ef2ce7e94324e5580526601336fa785/setup.py", line 21, in <module>
          long_description = (this_directory / "../README.md").read_text()
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/arnav/miniforge3/envs/splam/lib/python3.12/pathlib.py", line 1027, in read_text
          with self.open(mode='r', encoding=encoding, errors=errors) as f:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/arnav/miniforge3/envs/splam/lib/python3.12/pathlib.py", line 1013, in open
          return io.open(self, mode, buffering, encoding, errors, newline)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-2qrm2225/splam_5ef2ce7e94324e5580526601336fa785/../README.md'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by Kuanhao-Chao** [comment]
Hi @ArnavBharti,

Splam has not been added to Bioconda yet; currently, it is only available on PyPI. I tested it and encountered no errors when installing Splam version 1.0.10. Please try installing it again using the following command:
```
pip install splam==v1.0.10
```

If the issue persists, you can attempt installing it from the source. Refer to this page for detailed instructions: [Splam Installation Guide](https://ccb.jhu.edu/splam/content/installation.html#install-from-source).
Please let me know if it still doesn't work.

Kuan-Hao

**Comment by xiekunwhy** [comment]
hope to see splam on bioconda cloud some day, very hard to install using pip and manully.
