### ISSUE TITLE
Error when installing Splam via pip or source

### ISSUE THREAD

**Issue by wangdepin** [Kuanhao-Chao/splam#8]
Collecting splam==1.0.11
  Using cached splam-1.0.11.tar.gz (18.6 MB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: torch>=1.12.0 in /wrk-kappa/users/depinwan/bin/env-splam/lib/python3.10/site-packages (from splam==1.0.11) (2.4.1)
Requirement already satisfied: pybedtools>=0.9.0 in /wrk-kappa/users/depinwan/bin/env-splam/lib/python3.10/site-packages (from splam==1.0.11) (0.9.0)
Requirement already satisfied: gffutils>=0.10.0 in /wrk-kappa/users/depinwan/bin/env-splam/lib/python3.10/site-packages (from splam==1.0.11) (0.10)
Collecting progress>=1.0 (from splam==1.0.11)
  Using cached progress-1.6-py3-none-any.whl
Requirement already satisfied: pyfaidx>=0.5.5.2 in /wrk-kappa/users/depinwan/bin/env-splam/lib/python3.10/site-packages (from gffutils>=0.10.0->splam==1.0.11) (0.8.1.2)
Requirement already satisfied: six>=1.12.0 in /wrk-kappa/users/depinwan/bin/env-splam/lib/python3.10/site-packages (from gffutils>=0.10.0->splam==1.0.11) (1.16.0)
Requirement already satisfied: argh>=0.26.2 in /wrk-kappa/users/depinwan/bin/env-splam/lib/python3.10/site-packages (from gffutils>=0.10.0->splam==1.0.11) (0.31.3)
Requirement already satisfied: argcomplete>=1.9.4 in /wrk-kappa/users/depinwan/bin/env-splam/lib/python3.10/site-packages (from gffutils>=0.10.0->splam==1.0.11) (3.5.1)
Requirement already satisfied: simplejson in /wrk-kappa/users/depinwan/bin/env-splam/lib/python3.10/site-packages (from gffutils>=0.10.0->splam==1.0.11) (3.19.3)
Requirement already satisfied: pysam in /wrk-kappa/users/depinwan/bin/env-splam/lib/python3.10/site-packages (from pybedtools>=0.9.0->splam==1.0.11) (0.22.1)
Requirement already satisfied: filelock in /wrk-kappa/users/depinwan/bin/env-splam/lib/python3.10/site-packages (from torch>=1.12.0->splam==1.0.11) (3.16.1)
Requirement already satisfied: typing-extensions>=4.8.0 in /wrk-kappa/users/depinwan/bin/env-splam/lib/python3.10/site-packages (from torch>=1.12.0->splam==1.0.11) (4.12.2)
Requirement already satisfied: sympy in /wrk-kappa/users/depinwan/bin/env-splam/lib/python3.10/site-packages (from torch>=1.12.0->splam==1.0.11) (1.13.3)
Requirement already satisfied: networkx in /wrk-kappa/users/depinwan/bin/env-splam/lib/python3.10/site-packages (from torch>=1.12.0->splam==1.0.11) (3.3)
Requirement already satisfied: jinja2 in /wrk-kappa/users/depinwan/bin/env-splam/lib/python3.10/site-packages (from torch>=1.12.0->splam==1.0.11) (3.1.4)
Requirement already satisfied: fsspec in /wrk-kappa/users/depinwan/bin/env-splam/lib/python3.10/site-packages (from torch>=1.12.0->splam==1.0.11) (2024.9.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /wrk-kappa/users/depinwan/bin/env-splam/lib/python3.10/site-packages (from torch>=1.12.0->splam==1.0.11) (12.1.105)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /wrk-kappa/users/depinwan/bin/env-splam/lib/python3.10/site-packages (from torch>=1.12.0->splam==1.0.11) (12.1.105)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /wrk-kappa/users/depinwan/bin/env-splam/lib/python3.10/site-packages (from torch>=1.12.0->splam==1.0.11) (12.1.105)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /wrk-kappa/users/depinwan/bin/env-splam/lib/python3.10/site-packages (from torch>=1.12.0->splam==1.0.11) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /wrk-kappa/users/depinwan/bin/env-splam/lib/python3.10/site-packages (from torch>=1.12.0->splam==1.0.11) (12.1.3.1)
Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /wrk-kappa/users/depinwan/bin/env-splam/lib/python3.10/site-packages (from torch>=1.12.0->splam==1.0.11) (11.0.2.54)
Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /wrk-kappa/users/depinwan/bin/env-splam/lib/python3.10/site-packages (from torch>=1.12.0->splam==1.0.11) (10.3.2.106)
Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /wrk-kappa/users/depinwan/bin/env-splam/lib/python3.10/site-packages (from torch>=1.12.0->splam==1.0.11) (11.4.5.107)
Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /wrk-kappa/users/depinwan/bin/env-splam/lib/python3.10/site-packages (from torch>=1.12.0->splam==1.0.11) (12.1.0.106)
Requirement already satisfied: nvidia-nccl-cu12==2.20.5 in /wrk-kappa/users/depinwan/bin/env-splam/lib/python3.10/site-packages (from torch>=1.12.0->splam==1.0.11) (2.20.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /wrk-kappa/users/depinwan/bin/env-splam/lib/python3.10/site-packages (from torch>=1.12.0->splam==1.0.11) (12.1.105)
Requirement already satisfied: triton==3.0.0 in /wrk-kappa/users/depinwan/bin/env-splam/lib/python3.10/site-packages (from torch>=1.12.0->splam==1.0.11) (3.0.0)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /wrk-kappa/users/depinwan/bin/env-splam/lib/python3.10/site-packages (from nvidia-cusolver-cu12==11.4.5.107->torch>=1.12.0->splam==1.0.11) (12.6.77)
Requirement already satisfied: setuptools in /wrk-kappa/users/depinwan/bin/env-splam/lib/python3.10/site-packages (from pyfaidx>=0.5.5.2->gffutils>=0.10.0->splam==1.0.11) (75.1.0)
Requirement already satisfied: importlib-metadata in /wrk-kappa/users/depinwan/bin/env-splam/lib/python3.10/site-packages (from pyfaidx>=0.5.5.2->gffutils>=0.10.0->splam==1.0.11) (8.5.0)
Requirement already satisfied: packaging in /wrk-kappa/users/depinwan/bin/env-splam/lib/python3.10/site-packages (from pyfaidx>=0.5.5.2->gffutils>=0.10.0->splam==1.0.11) (24.1)
Requirement already satisfied: MarkupSafe>=2.0 in /wrk-kappa/users/depinwan/bin/env-splam/lib/python3.10/site-packages (from jinja2->torch>=1.12.0->splam==1.0.11) (2.1.5)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /wrk-kappa/users/depinwan/bin/env-splam/lib/python3.10/site-packages (from sympy->torch>=1.12.0->splam==1.0.11) (1.3.0)
Requirement already satisfied: zipp>=3.20 in /wrk-kappa/users/depinwan/bin/env-splam/lib/python3.10/site-packages (from importlib-metadata->pyfaidx>=0.5.5.2->gffutils>=0.10.0->splam==1.0.11) (3.20.2)
Building wheels for collected packages: splam
  Building wheel for splam (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [121 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build/lib.linux-x86_64-cpython-310/splam
      copying splam/__init__.py -> build/lib.linux-x86_64-cpython-310/splam
      copying splam/chr_size.py -> build/lib.linux-x86_64-cpython-310/splam
      copying splam/clean_gff.py -> build/lib.linux-x86_64-cpython-310/splam
      copying splam/config.py -> build/lib.linux-x86_64-cpython-310/splam
      copying splam/extract_gff.py -> build/lib.linux-x86_64-cpython-310/splam
      copying splam/header.py -> build/lib.linux-x86_64-cpython-310/splam
      copying splam/main.py -> build/lib.linux-x86_64-cpython-310/splam
      copying splam/parse.py -> build/lib.linux-x86_64-cpython-310/splam
      copying splam/prediction.py -> build/lib.linux-x86_64-cpython-310/splam
      copying splam/splam.py -> build/lib.linux-x86_64-cpython-310/splam
      running build_ext
      CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
        Compatibility with CMake < 3.5 will be removed from a future version of
        CMake.
      
        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.
      
      
      -- The C compiler identification is GNU 8.5.0
      -- The CXX compiler identification is GNU 8.5.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      CMake Deprecation Warning at pybind11/CMakeLists.txt:8 (cmake_minimum_required):
        Compatibility with CMake < 3.5 will be removed from a future version of
        CMake.
      
        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.
      
      
      -- pybind11 v2.11.0 dev1
      CMake Warning (dev) at pybind11/tools/FindPythonLibsNew.cmake:98 (find_package):
        Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
        are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
        the cmake_policy command to set the policy and suppress this warning.
      
      Call Stack (most recent call first):
        pybind11/tools/pybind11Tools.cmake:50 (find_package)
        pybind11/tools/pybind11Common.cmake:180 (include)
        pybind11/CMakeLists.txt:210 (include)
      This warning is for project developers.  Use -Wno-dev to suppress it.
      
      -- Found PythonInterp: /wrk-kappa/users/depinwan/bin/env-splam/bin/python3.10 (found suitable version "3.10.14", minimum required is "3.6")
      -- Found PythonLibs: /wrk-kappa/users/depinwan/bin/env-splam/lib/libpython3.10.so
      -- Performing Test HAS_FLTO
      -- Performing Test HAS_FLTO - Success
      -- Found ZLIB: /usr/lib64/libz.so (found version "1.2.11")
      /tmp/pip-install-sn48uc0z/splam_b4d0d3fee2364291b6b54950fd948ad6/include/htslib
      LIBRARY_OUTPUT_DIRECTORY:
      EXAMPLE_VERSION_INFO: 1.0.11
      -- Configuring done (2.0s)
      -- Generating done (0.0s)
      -- Build files have been written to: /tmp/pip-install-sn48uc0z/splam_b4d0d3fee2364291b6b54950fd948ad6/build/temp.linux-x86_64-cpython-310/splam_extract
      [  2%] Creating directories for 'htslib'
      [  5%] No download step for 'htslib'
      [  8%] No update step for 'htslib'
      [ 11%] No patch step for 'htslib'
      [ 14%] Performing configure step for 'htslib'
      /bin/sh: autoreconf: command not found
      gmake[2]: *** [CMakeFiles/htslib.dir/build.make:92: htslib-prefix/src/htslib-stamp/htslib-configure] Error 127
      gmake[1]: *** [CMakeFiles/Makefile2:104: CMakeFiles/htslib.dir/all] Error 2
      gmake: *** [Makefile:91: all] Error 2
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-sn48uc0z/splam_b4d0d3fee2364291b6b54950fd948ad6/setup.py", line 136, in <module>
          setup(
        File "/wrk-kappa/users/depinwan/bin/env-splam/lib/python3.10/site-packages/setuptools/__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
        File "/wrk-kappa/users/depinwan/bin/env-splam/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 183, in setup
          return run_commands(dist)
        File "/wrk-kappa/users/depinwan/bin/env-splam/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 199, in run_commands
          dist.run_commands()
        File "/wrk-kappa/users/depinwan/bin/env-splam/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
          self.run_command(cmd)
        File "/wrk-kappa/users/depinwan/bin/env-splam/lib/python3.10/site-packages/setuptools/dist.py", line 950, in run_command
          super().run_command(command)
        File "/wrk-kappa/users/depinwan/bin/env-splam/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/wrk-kappa/users/depinwan/bin/env-splam/lib/python3.10/site-packages/setuptools/command/bdist_wheel.py", line 398, in run
          self.run_command("build")
        File "/wrk-kappa/users/depinwan/bin/env-splam/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/wrk-kappa/users/depinwan/bin/env-splam/lib/python3.10/site-packages/setuptools/dist.py", line 950, in run_command
          super().run_command(command)
        File "/wrk-kappa/users/depinwan/bin/env-splam/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/wrk-kappa/users/depinwan/bin/env-splam/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/wrk-kappa/users/depinwan/bin/env-splam/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/wrk-kappa/users/depinwan/bin/env-splam/lib/python3.10/site-packages/setuptools/dist.py", line 950, in run_command
          super().run_command(command)
        File "/wrk-kappa/users/depinwan/bin/env-splam/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/wrk-kappa/users/depinwan/bin/env-splam/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 98, in run
          _build_ext.run(self)
        File "/wrk-kappa/users/depinwan/bin/env-splam/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
          self.build_extensions()
        File "/wrk-kappa/users/depinwan/bin/env-splam/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 476, in build_extensions
          self._build_extensions_serial()
        File "/wrk-kappa/users/depinwan/bin/env-splam/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 502, in _build_extensions_serial
          self.build_extension(ext)
        File "/tmp/pip-install-sn48uc0z/splam_b4d0d3fee2364291b6b54950fd948ad6/setup.py", line 129, in build_extension
          subprocess.run(
        File "/wrk-kappa/users/depinwan/bin/env-splam/lib/python3.10/subprocess.py", line 526, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['cmake', '--build', '.']' returned non-zero exit status 2.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for splam
  Running setup.py clean for splam
Failed to build splam
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (splam)

**Comment by abearab** [comment]
I'm getting same error :(
